In [1]:
import requests
import json, pandas as pd, numpy as np

In [2]:
temp = pd.read_csv("../grfs_test.csv")
temp.head()

,pt_age,dx_to_sct,height_tx,weight_tx,bmi,cbt_tnc_kg_cryop,cbt_cfugm_kg,cbt_cd34_kg,cbt_tnc_kg_cryop_mis,source,...,cond,tcd_invivo,hctci_points_corr,seromis6abdr,genomis6abdr,rcmvab,dcmvab,cmvab_cat1,event_grfs,time_grfs
0,42,209.0,158.300000,49.600000,19.793375,999.00000,999.00000,999.00000,1,1,...,1.0,0.0,0.0,0.0,0.0,0,1,1,1,7.633333
1,59,211.0,172.000000,65.000000,21.971336,3.48923,42.38462,0.80769,0,4,...,5.0,0.0,1.0,2.0,4.0,0,0,0,1,0.633333
2,54,295.0,162.000000,52.000000,19.814053,999.00000,999.00000,999.00000,1,1,...,5.0,0.0,0.0,0.0,2.0,9,9,9,1,4.566667
3,62,952.0,158.606496,56.206215,21.466732,999.00000,999.00000,999.00000,1,2,...,5.0,0.0,0.0,0.0,0.0,9,9,9,1,7.266667
4,66,110.0,147.000000,50.000000,23.138507,999.00000,999.00000,999.00000,1,1,...,5.0,0.0,0.0,0.0,1.0,0,1,1,1,0.400000

In [4]:
temp.iloc[1].pt_age

59.0

In [7]:
response = requests.get("http://127.0.0.1:8000/predict"
    , headers={"Content-Type": "application/json"}
    , data=json.dumps({'pt_age':temp.iloc[2].pt_age, 'dx_to_sct':temp.iloc[2].dx_to_sct, 'height_tx':temp.iloc[1].height_tx, 'weight_tx':temp.iloc[1].weight_tx, 
                       'bmi':temp.iloc[2].bmi, 'cbt_tnc_kg_cryop':temp.iloc[1].cbt_tnc_kg_cryop, 'cbt_cfugm_kg':temp.iloc[1].cbt_cfugm_kg, 
                       'cbt_cd34_kg':temp.iloc[1].cbt_cd34_kg, 'cbt_tnc_kg_cryop_mis':temp.iloc[1].cbt_tnc_kg_cryop_mis, 'source':temp.iloc[1].source, 
                       'donor_cd':temp.iloc[1].donor_cd, 'sct_type':temp.iloc[1].sct_type, 'pt_sex':temp.iloc[1].pt_sex, 'sex_mismatch1':temp.iloc[1].sex_mismatch1, 
                       'ps24':temp.iloc[1].ps24, 'abo_mismatch':temp.iloc[1].abo_mismatch, 'diagnosis':temp.iloc[1].diagnosis, 'stage5':temp.iloc[1].stage5, 
                       'stage_dri':temp.iloc[1].stage_dri, 'tbi':temp.iloc[1].tbi, 'cond':temp.iloc[1].cond, 'tcd_invivo':temp.iloc[1].tcd_invivo, 
                       'hctci_points_corr':temp.iloc[1].hctci_points_corr, 'seromis6abdr':temp.iloc[1].seromis6abdr, 'genomis6abdr':temp.iloc[1].genomis6abdr, 
                       'rcmvab':temp.iloc[1].rcmvab, 'dcmvab':temp.iloc[1].dcmvab, 'cmvab_cat1':temp.iloc[1].cmvab_cat1})
)
print(response.json())

{'error': ['500 - Internal server error']}